import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { getS3BucketDirectoryListing } from '../utils/aws/getS3BucketDirectoryListing';
import Link from 'next/link';

const Home: NextPage = () => {
  const [files, setFiles] = useState([]);
  const [directories, setDirectories] = useState([]);
  const [isLoading, setLoading] = useState(false);

  const { query } = useRouter();

  useEffect(() => {
    setLoading(true);

    const s3Path = query.path ?? '';

    const s3ApiUri = `/api/s3?path=${s3Path}`;

    fetch(s3ApiUri)
      .then((res) => res.json())
      .then((data) => {
        setFiles(data.files);
        setDirectories(data.directories);

        setLoading(false);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>S3 Private Bucket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ul>
          {!isLoading &&
            directories.map((directory: any) => (
              <li key={directory.Key}>
                <Link href={'?path=' + directory.Key}>{directory.Display}</Link>
              </li>
            ))}
          {!isLoading &&
            [...files].map((file: any) => (
              <li key={file.key}>
                <a href={file.downloadUri}>{file.key}</a>
              </li>
            ))}
        </ul>
      </div>
    </div>
  );
};

export default Home;
